import type { Metadata } from "next";

import "./globals.css";
import { ContextProvider } from "@/context/Context";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="p-0 m-0  bg-neutral-100 ">
        <header className="text-left text-3xl p-5 font-bold  text-neutral-600">
          Baldwin Bookin
        </header>
        <div className="px-20  ">
          <ContextProvider>{children}</ContextProvider>
        </div>
      </body>
    </html>
  );
}
